### PR TITLE
fix: KMAC compute deterministic & Policy edit edgecase

### LINKED ISSUE #95: Add dynamicity in key management
In CoverCrypt, we have the following properties:

- the number of attribute values grows with the number of attribute modifications performed: rotations add a new value for an existing attribute while attribute creations add a new attribute with a new value;
- the number of partitions is equal to the number of combinations of attribute values that can be created by using one value associated to an attribute from each axis;
- the number of keys in each master key is equal to the number of partitions that can be created using their associated policy.

Hence, if a great number of attributes are created or a great number of rotations are performed, the size of both the policy and the master keys will grow drastically.

To prevent this, we need to allow dropping attribute values from the policy:
- removing an attribute from a policy axis could prevent the number of attributes from growing too big;
- retaining only a given number of values per attribute could allow purging the policy from old rotated attribute values.

Then a master key update should synchronize the master keys with the updated policy.

**Note**: this is not a problem for user secret keys since they generally hold a small subset of the policy rights; they also can be purged from old sub-keys at each refresh by setting the `keep_old_rights` parameter to `false` which prevents rotations from rendering them unmanageable.

### PR DESCRIPTION
**Pull request by ackRow**
Closes #95

### CODE REVIEW

File: src/abe_policy/dimension.rs [hunk 1]
```diff
@@ -265,17 +268,23 @@ impl Dimension {
...
-                    Ok(())
+            ));
+        }
+        match self.attributes.remove(attr_name) {
+            Some(attr_params) => {
+                self.attributes.insert(new_name.to_string(), attr_params);
+                if let Some(order) = self.order.as_mut() {
+                    order.iter_mut().for_each(|name| {
+                        if name == attr_name {
+                            *name = new_name.to_string()
```
Comment (tbrezot) [inline src/abe_policy/dimension.rs:281]: You may not need to store owned string object, but a reference to attribute names stored in the `self.attributes`. This would be a way to avoid cloning here (plus take ownership of `new_name` in this function as you need it).

File: src/abe_policy/policy.rs [hunk 2]
```diff
@@ -164,7 +169,10 @@ impl Policy {
         if let Some(dim) = self.dimensions.get(&attr.dimension) {
             dim.attributes
                 .get(&attr.name)
-                .ok_or(Error::AttributeNotFound(attr.name.to_string()))
+                .ok_or(Error::AttributeNotFound(format!(
+                    "{}::{}",
+                    attr.dimension, attr.name
+                )))
```
Comment (tbrezot) [inline src/abe_policy/policy.rs:175]: Doesn't Attribute implement Display ?

```suggestion
                .ok_or(Error::AttributeNotFound(attr.to_string()))
```

File: src/core/primitives.rs [hunk 3]
```diff
@@ -41,6 +41,7 @@ fn compute_user_key_kmac(msk: &MasterSecretKey, usk: &UserSecretKey) -> Option<K
     user_key_bytes.extend_from_slice(&usk.a.to_bytes());
     user_key_bytes.extend_from_slice(&usk.b.to_bytes());
 
+    // KMAC is deterministic because subkeys is a Vec preserving keys order
```
Comment (tbrezot) [inline src/core/primitives.rs:44]: How does this comment help understanding the code here? Wouldn't it make more sense somewhere else (e.g. to justify the use of a `Vec` for the list of subkeys)? Is it necessary?

File: src/core/primitives.rs [hunk 4]
```diff
@@ -291,20 +293,14 @@ pub fn update(
...
-                let (pk_i, _) = mpk.subkeys.get(partition).ok_or_else(|| {
-                    Error::KeyError(
-                        "Kyber public key cannot be computed from the secret key.".to_string(),
-                    )
-                })?;
+                let pk_i = mpk
+                    .subkeys
+                    .get(partition)
+                    .map(|(pk_i, _)| pk_i)
+                    .unwrap_or(&None);
```
Comment (tbrezot) [inline src/core/primitives.rs:300]: You can compute this in the if sk_i.is_some() {...} branch to avoid needless computation.

File: src/core/primitives.rs [hunk 5]
```diff
@@ -41,6 +41,7 @@ fn compute_user_key_kmac(msk: &MasterSecretKey, usk: &UserSecretKey) -> Option<K
     user_key_bytes.extend_from_slice(&usk.a.to_bytes());
```
Comment (tbrezot) [inline src/core/primitives.rs:41]: I cannot comment on the exact line, but you are not allocating enough bytes to store Kyber keys if there are some. Plus, I would prefer all this to be inside a `map(|kmac_key| ...)` or a `if let Some(kmac_key) = &msk.kmac_key {` branche to avoid unneeded computation.

**Review by tbrezot — APPROVED** [review]

File: src/core/primitives.rs (hunk 5 above)
Comment (ackRow) [reply src/core/primitives.rs]: to compute the right size to allocate we would need to iterate through the subkeys, is it worth it?
Maybe a "good enough" estimation for the size to allocate is the best solution here?

Comment (ackRow) [reply src/core/primitives.rs]: solved by computing the KMAC directly instead of allocating a temporary vec
